load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "bouncing_ball",
    srcs = ["bouncing_ball/ball.cpp"],
    deps = [
        "//core",
        "//engine",
    ],
)

cc_binary(
    name = "spaceship",
    srcs = ["spaceship/spaceship.cpp"],
    data = ["spaceship/spaceship.glb"],
    deps = [
        "//core",
        "//engine",
    ],
)
