name: build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: 
      image: ghcr.io/antsoh161/ubuntu2310-vulkan:latest
      credentials:
        username: antsoh161
        password: ${{ secrets.MEDDL_DOCKER_REGISTRY_TOKEN }}

    strategy:
      fail-fast: true 
      matrix:
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        #build_type: [Release, Debug]
        build_type: [Release]
        #compilers: [ {c: gcc, cpp: g++}, {c: clang, cpp: clang++}, {c: cl, cpp: cl}]
        compilers:
        - {c: gcc, cpp: g++}
        - {c: clang-17, cpp: clang++-17} 

    steps:
    - uses: actions/checkout@v4

    - name: cmake
      run: cmake -DCMAKE_C_COMPILER=${{ matrix.compilers.c }} -DCMAKE_CXX_COMPILER=${{ matrix.compilers.cpp }} --preset ${{ matrix.build_type }}

    - name: cmake build
      run: cmake --build --preset ${{ matrix.build_type }}
