name: build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: 
      image: ghcr.io/antsoh161/ubuntu2310-vulkan:latest
      credentials:
        username: antsoh161
        password: ${{ secrets.MEDDL_DOCKER_REGISTRY_TOKEN }}

    strategy:
      fail-fast: true 
      matrix:
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        build_type: [Release]
        cxx_compiler: [g++, clang++, cl]
        c_compiler: [gcc, clang, cl]
        include:
          - os: ubuntu-latest
            cxx_compiler: g++
            c_compiler: gcc
        exclude:
          - os: ubuntu-latest
            c_compiler: cl
            cxx_compiler: cl
          - os: ubuntu-latest
            c_compiler: clang
            cxx_compiler: clang++

    steps:
    - uses: actions/checkout@v4

    - name: cmake
      run: cmake -DCMAKE_C_COMPILER= ${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }} --preset ${{ matrix.build_type }}

    - name: cmake build
      run: cmake --build --preset ${{ matrix.build_type }}
